apiVersion: v1
kind: Service
metadata:
  name: ml7ma-frontend
  labels:
    app: ml7ma-frontend
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: ml7ma-frontend