apiVersion: batch/v1
kind: Job
metadata:
  name: mysql-init-superuser-job
spec:
  backoffLimit: 4
  template:
    spec:
      containers:
        - name: django
          image: borhom11/backend:1.0.1
          command: ["/bin/bash", "-c"]
          args:
            - "python manage.py createsuperuser --no-input"
          envFrom:
            - secretRef:
                name: mysql-secret
      restartPolicy: Never
