apiVersion: v1
kind: Service
metadata:
  name: ml7ma-backend
  labels:
    app: ml7ma-backend
spec:
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: ml7ma-backend