global:
  domain: www.ml7ma.com
  apiDomain: www.ml7maapi.com

frontend:
  name: ml7ma-frontend
  image:
    repository: borhom11/frontend
    tag: 1.0.5
    pullPolicy: IfNotPresent
  replicaCount: 2
  resources:
    requests:
      memory: "128Mi"
      cpu: "250m"
    limits:
      memory: "256Mi"
      cpu: "500m"
  service:
    port: 80
    targetPort: 80
  config:
     serverUrl: "http://www.ml7maapi.com/shop"
     authUrl: "http://www.ml7maapi.com/auth"

backend:
  name: ml7ma-backend
  image:
    repository: borhom11/backend
    tag: 1.0.1
    pullPolicy: IfNotPresent
  replicaCount: 1
  service:
    port: 8000
    targetPort: 8000

mysql:
  name: ml7ma-mysql
  image:
    repository: mysql
    tag: 8.0.11
    pullPolicy: IfNotPresent
  replicaCount: 1
  service:
    port: 3306
    targetPort: 3306
  storage:
    size: 5Gi
    storageClassName: local-path
  rootPassword: eladwy  
  database: meatshop

djangoSuperuser:
  username: admin
  email: ahmedibrahiem111@gmail.com
  password: LmWf8d@5