apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.backend.name }}
  labels:
    app: {{ .Release.Name }}-{{ .Values.backend.name }}
spec:
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
      protocol: TCP
  selector:
    app: {{ .Release.Name }}-{{ .Values.backend.name }}