apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Values.frontend.name }}-config
data:
  config.json: |-
    {
      "SERVER_URL": "{{ .Values.frontend.config.serverUrl }}",
      "AUTH_URL": "{{ .Values.frontend.config.authUrl }}"
    }