apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.frontend.name }}
  labels:
    app: {{ .Release.Name }}-{{ .Values.frontend.name }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Values.frontend.name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Values.frontend.name }}
    spec:
      containers:
        - name: {{ .Release.Name }}-{{ .Values.frontend.name }}
          image: {{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.service.targetPort }}
              name: http
          volumeMounts:
            - name: {{ .Release.Name }}-{{ .Values.frontend.name }}-config
              mountPath: /usr/share/nginx/html/config.json
              subPath: config.json
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
      volumes:
        - name: {{ .Release.Name }}-{{ .Values.frontend.name }}-config
          configMap:
            name: {{ .Release.Name }}-{{ .Values.frontend.name }}-config