apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-{{.Values.mysql.name}}-init
  labels:
    app: {{ .Release.Name }}-{{.Values.mysql.name}}
spec:
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{.Values.mysql.name}}
    spec:
      restartPolicy: OnFailure
      containers:
        - name: mysql-init
          image: {{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}
          command: ["/bin/sh", "-c"]
          args:
            - |
              mysql -h${MYSQL_HOST} -u root -p${MYSQL_ROOT_PASSWORD} <<EOF
              CREATE DATABASE IF NOT EXISTS {{ .Values.mysql.database }};
              EOF
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MYSQL_ROOT_PASSWORD
                  name: be-secret
            - name: MYSQL_HOST
              valueFrom:
                secretKeyRef:
                  key: LOCAL_DB_HOST
                  name: mysql-secret