apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{.Values.mysql.name}}-svc
  labels:
    app: {{ .Release.Name }}-{{.Values.mysql.name}}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.mysql.service.port }}
  clusterIP: None
  selector:
    app: {{ .Release.Name }}-{{.Values.mysql.name}}