apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-{{.Values.mysql.name}}
  labels:
    app: {{ .Release.Name }}-{{.Values.mysql.name}}
spec:
  serviceName: {{ .Release.Name }}-{{.Values.mysql.name}}
  replicas: {{.Values.mysql.replicaCount}}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{.Values.mysql.name}}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{.Values.mysql.name}}
    spec:
      containers:
        - name: mysql
          image: {{ .Values.mysql.image.repository }}:{{.Values.mysql.image.tag}}
          ports:
            - containerPort: {{.Values.mysql.service.targetPort}}
              name: {{ .Values.mysql.image.repository }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MYSQL_ROOT_PASSWORD
                  name: be-secret
           
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: mysql-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{.Values.mysql.storage.size}}
        storageClassName: {{.Values.mysql.storage.storageClassName}}
