apiVersion: v1
kind: Secret
metadata:
  name: be-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.rootPassword | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  DB_NAME: {{ .Values.mysql.database | b64enc }}
  DB_PORT: {{ .Values.mysql.service.port | toString | b64enc }}
  LOCAL_DB_HOST: {{ printf "%s-%s-svc" .Release.Name .Values.mysql.name | b64enc }}
  LOCAL_DB_PASSWORD: {{ .Values.mysql.rootPassword | b64enc }}
  LOCAL_DB_USER: {{ "root" | b64enc }}
  DJANGO_SUPERUSER_EMAIL: {{ .Values.djangoSuperuser.email | b64enc }}
  DJANGO_SUPERUSER_USERNAME: {{ .Values.djangoSuperuser.username | b64enc }}
  DJANGO_SUPERUSER_PASSWORD: {{ .Values.djangoSuperuser.password | b64enc }}