apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-mysql-init-superuser-job
spec:
  backoffLimit: 4
  template:
    spec:
      containers:
        - name: django
          image: {{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}
          command: ["/bin/bash", "-c"]
          args:
            - "python manage.py createsuperuser --no-input"
          envFrom:
            - secretRef:
                name: mysql-secret
      restartPolicy: Never